// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/adexcell/delayed-notifier/internal/domain (interfaces: NotifyRedis)
//
// Generated by this command:
//
//	mockgen -destination=mock_redis.go -package=mocks github.com/adexcell/delayed-notifier/internal/domain NotifyRedis
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/adexcell/delayed-notifier/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockNotifyRedis is a mock of NotifyRedis interface.
type MockNotifyRedis struct {
	ctrl     *gomock.Controller
	recorder *MockNotifyRedisMockRecorder
	isgomock struct{}
}

// MockNotifyRedisMockRecorder is the mock recorder for MockNotifyRedis.
type MockNotifyRedisMockRecorder struct {
	mock *MockNotifyRedis
}

// NewMockNotifyRedis creates a new mock instance.
func NewMockNotifyRedis(ctrl *gomock.Controller) *MockNotifyRedis {
	mock := &MockNotifyRedis{ctrl: ctrl}
	mock.recorder = &MockNotifyRedisMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifyRedis) EXPECT() *MockNotifyRedisMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockNotifyRedis) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockNotifyRedisMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockNotifyRedis)(nil).Close))
}

// Get mocks base method.
func (m *MockNotifyRedis) Get(ctx context.Context, id string) (*domain.Notify, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Notify)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNotifyRedisMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNotifyRedis)(nil).Get), ctx, id)
}

// SetWithExpiration mocks base method.
func (m *MockNotifyRedis) SetWithExpiration(ctx context.Context, n *domain.Notify) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWithExpiration", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWithExpiration indicates an expected call of SetWithExpiration.
func (mr *MockNotifyRedisMockRecorder) SetWithExpiration(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWithExpiration", reflect.TypeOf((*MockNotifyRedis)(nil).SetWithExpiration), ctx, n)
}
