// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/adexcell/delayed-notifier/internal/domain (interfaces: QueueProvider)
//
// Generated by this command:
//
//	mockgen -destination=mock_queue.go -package=mocks github.com/adexcell/delayed-notifier/internal/domain QueueProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/adexcell/delayed-notifier/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockQueueProvider is a mock of QueueProvider interface.
type MockQueueProvider struct {
	ctrl     *gomock.Controller
	recorder *MockQueueProviderMockRecorder
	isgomock struct{}
}

// MockQueueProviderMockRecorder is the mock recorder for MockQueueProvider.
type MockQueueProviderMockRecorder struct {
	mock *MockQueueProvider
}

// NewMockQueueProvider creates a new mock instance.
func NewMockQueueProvider(ctrl *gomock.Controller) *MockQueueProvider {
	mock := &MockQueueProvider{ctrl: ctrl}
	mock.recorder = &MockQueueProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueProvider) EXPECT() *MockQueueProviderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockQueueProvider) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockQueueProviderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockQueueProvider)(nil).Close))
}

// Consume mocks base method.
func (m *MockQueueProvider) Consume(ctx context.Context, handler domain.MessageHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockQueueProviderMockRecorder) Consume(ctx, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockQueueProvider)(nil).Consume), ctx, handler)
}

// Init mocks base method.
func (m *MockQueueProvider) Init() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init")
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockQueueProviderMockRecorder) Init() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockQueueProvider)(nil).Init))
}

// Publish mocks base method.
func (m *MockQueueProvider) Publish(ctx context.Context, n *domain.Notify) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockQueueProviderMockRecorder) Publish(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockQueueProvider)(nil).Publish), ctx, n)
}
