// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/adexcell/delayed-notifier/internal/domain (interfaces: NotifyPostgres)
//
// Generated by this command:
//
//	mockgen -destination=mock_postgres.go -package=mocks github.com/adexcell/delayed-notifier/internal/domain NotifyPostgres
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/adexcell/delayed-notifier/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockNotifyPostgres is a mock of NotifyPostgres interface.
type MockNotifyPostgres struct {
	ctrl     *gomock.Controller
	recorder *MockNotifyPostgresMockRecorder
	isgomock struct{}
}

// MockNotifyPostgresMockRecorder is the mock recorder for MockNotifyPostgres.
type MockNotifyPostgresMockRecorder struct {
	mock *MockNotifyPostgres
}

// NewMockNotifyPostgres creates a new mock instance.
func NewMockNotifyPostgres(ctrl *gomock.Controller) *MockNotifyPostgres {
	mock := &MockNotifyPostgres{ctrl: ctrl}
	mock.recorder = &MockNotifyPostgresMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifyPostgres) EXPECT() *MockNotifyPostgresMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockNotifyPostgres) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockNotifyPostgresMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockNotifyPostgres)(nil).Close))
}

// Create mocks base method.
func (m *MockNotifyPostgres) Create(ctx context.Context, n *domain.Notify) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotifyPostgresMockRecorder) Create(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotifyPostgres)(nil).Create), ctx, n)
}

// DeleteByID mocks base method.
func (m *MockNotifyPostgres) DeleteByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockNotifyPostgresMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockNotifyPostgres)(nil).DeleteByID), ctx, id)
}

// GetNotifyByID mocks base method.
func (m *MockNotifyPostgres) GetNotifyByID(ctx context.Context, id string) (*domain.Notify, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotifyByID", ctx, id)
	ret0, _ := ret[0].(*domain.Notify)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotifyByID indicates an expected call of GetNotifyByID.
func (mr *MockNotifyPostgresMockRecorder) GetNotifyByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotifyByID", reflect.TypeOf((*MockNotifyPostgres)(nil).GetNotifyByID), ctx, id)
}

// List mocks base method.
func (m *MockNotifyPostgres) List(ctx context.Context, limit, offset int) ([]*domain.Notify, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]*domain.Notify)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockNotifyPostgresMockRecorder) List(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNotifyPostgres)(nil).List), ctx, limit, offset)
}

// LockAndFetchReady mocks base method.
func (m *MockNotifyPostgres) LockAndFetchReady(ctx context.Context, limit int, visibilityTimeout time.Duration) ([]*domain.Notify, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockAndFetchReady", ctx, limit, visibilityTimeout)
	ret0, _ := ret[0].([]*domain.Notify)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockAndFetchReady indicates an expected call of LockAndFetchReady.
func (mr *MockNotifyPostgresMockRecorder) LockAndFetchReady(ctx, limit, visibilityTimeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockAndFetchReady", reflect.TypeOf((*MockNotifyPostgres)(nil).LockAndFetchReady), ctx, limit, visibilityTimeout)
}

// UpdateStatus mocks base method.
func (m *MockNotifyPostgres) UpdateStatus(ctx context.Context, id string, status domain.Status, scheduledAt *time.Time, retryCount int, lastErr *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, scheduledAt, retryCount, lastErr)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockNotifyPostgresMockRecorder) UpdateStatus(ctx, id, status, scheduledAt, retryCount, lastErr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockNotifyPostgres)(nil).UpdateStatus), ctx, id, status, scheduledAt, retryCount, lastErr)
}
