// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/adexcell/delayed-notifier/internal/domain (interfaces: NotifyUsecase)
//
// Generated by this command:
//
//	mockgen -destination=mock_usecase.go -package=mocks github.com/adexcell/delayed-notifier/internal/domain NotifyUsecase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/adexcell/delayed-notifier/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockNotifyUsecase is a mock of NotifyUsecase interface.
type MockNotifyUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockNotifyUsecaseMockRecorder
	isgomock struct{}
}

// MockNotifyUsecaseMockRecorder is the mock recorder for MockNotifyUsecase.
type MockNotifyUsecaseMockRecorder struct {
	mock *MockNotifyUsecase
}

// NewMockNotifyUsecase creates a new mock instance.
func NewMockNotifyUsecase(ctrl *gomock.Controller) *MockNotifyUsecase {
	mock := &MockNotifyUsecase{ctrl: ctrl}
	mock.recorder = &MockNotifyUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifyUsecase) EXPECT() *MockNotifyUsecaseMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockNotifyUsecase) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNotifyUsecaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNotifyUsecase)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockNotifyUsecase) GetByID(ctx context.Context, id string) (*domain.Notify, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Notify)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockNotifyUsecaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockNotifyUsecase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockNotifyUsecase) List(ctx context.Context, limit, offset int) ([]*domain.Notify, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]*domain.Notify)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockNotifyUsecaseMockRecorder) List(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNotifyUsecase)(nil).List), ctx, limit, offset)
}

// Save mocks base method.
func (m *MockNotifyUsecase) Save(ctx context.Context, n *domain.Notify) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, n)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockNotifyUsecaseMockRecorder) Save(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockNotifyUsecase)(nil).Save), ctx, n)
}
